# Generated by Django 5.1.5 on 2025-01-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urunler", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kategoriler",
            options={"verbose_name": "Kategori", "verbose_name_plural": "Kategoriler"},
        ),
        migrations.AddField(
            model_name="kategoriler",
            name="ustkategori",
            field=models.ForeignKey(
                blank=True,
                help_text="Üst Kategori",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="urunler.kategoriler",
            ),
        ),
    ]
