# Generated by Django 5.1.5 on 2025-01-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urunler", "0007_etiketler_urunler_etiketler"),
    ]

    operations = [
        migrations.AddField(
            model_name="urunler",
            name="anasayfa",
            field=models.BooleanField(default=False),
        ),
    ]
