# Generated by Django 5.1.5 on 2025-01-29 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urunler", "0008_urunler_anasayfa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Varyasyonlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("varyasyon", models.CharField(max_length=155)),
                ("fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stok", models.PositiveIntegerField()),
                ("aktifmi", models.BooleanField(default=True)),
                (
                    "resim",
                    models.ImageField(
                        blank=True, null=True, upload_to="varyasyonresimleri"
                    ),
                ),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="urunler.urunler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Varyasyon",
                "verbose_name_plural": "Varyasyonlar",
            },
        ),
    ]
